title: Mert Yiğit
logo: /assets/pp.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal


Applications:
  - title: Budget Manager
    image: /assets/budget_manager.png
    description: This application is a budget management app for Android developed using Kotlin. It utilizes SQLite for local data storage, incorporates secure authentication and cloud storage with Firebase, supports complex mathematical operations, and includes robust data visualization capabilities.
    repo: https://github.com/MertYigit0/BudgetManager
  - title: Quick Recipes
    image: /assets/quick_recipes.png
    description: QuickRecipes is an Android application developed in Java that allows users to browse and discover various recipes.
    repo: https://github.com/MertYigit0/QuickRecipes
  - title: Space Escape
    image: /assets/space_escape.png
    description: Space Escape is a Hyper-Casual mobile game for Android devices that I 
    developed using Java and the LibGDX framework. It showcases spacethemed gameplay with smooth physics and an engaging user interface.
    repo: https://github.com/MertYigit0/Space-Escape-Android-Mobile-Game
